=== futre153/bbb/EManager/src/org/pabk/application/emanager/resource/xsd/module_list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/module_list" xmlns:tns="http://www.example.org/module_list" elementFormDefault="qualified">



    <element name="module-list" type="tns:ModuleListType"></element>

    <complexType name="ModuleListType">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="module" type="tns:ModuleType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="ModuleType">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="module-name" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="module-class" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="module-priority" type="int" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="module-description" type="string"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="required-modules"
    			type="tns:RequiredModulesType" minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="critical" type="boolean" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="RequiredModulesType">
    	<sequence minOccurs="0" maxOccurs="1">
    		<element name="module-name" type="string" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
</schema>

=== futre153/bbb/EManager/src/org/pabk/application/emanager/resource/xml/module-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<module-list xmlns="http://www.example.org/module_list" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/module_list ../xsd/module_list.xsd ">
  <module>
    <module-name>manager</module-name>
    <module-class>org.pabk.application.emanager.module.EventManager</module-class>
    <module-priority>0</module-priority>
    <module-description>Hlavný modul pre aplikáciu Event Manager. Nahrá ostatné moduly a riadi ich beh. Musí mať prioritu 0, pretože priorita nula sa spustí ako prvá.</module-description>
    <required-modules>
    	<module-name>DBConnector</module-name>
    	<module-name>GUIManager</module-name>
    </required-modules>
    <critical>true</critical>
  </module>
  <module>
  <module-name>DBConnector</module-name>
  <module-class>org.pabk.application.emanager.module.DBConnector</module-class>
  <module-priority>1</module-priority>
  <module-description>modul pre spojenie s databázou</module-description>
  <required-modules/>
  <critical>true</critical>
  </module>
  <module>
  	<module-name>GUIManager</module-name>
  	<module-class>org.pabk.application.emanager.module.GUIManager</module-class>
  	<module-priority>1</module-priority>
  	<module-description>Module for GUI management</module-description>
  	<required-modules>
  		<module-name>DBConnector</module-name>
  		<module-name>Routing</module-name>
  	</required-modules>
  	<critical>true</critical>
  </module>
  <module>
  	<module-name>Routing</module-name>
  	<module-class>org.pabk.application.emanager.module.Routing</module-class>
  	<module-priority>1</module-priority>
  	<module-description>Module for creating and routing email messages</module-description>
  	<required-modules>
  		<module-name>DBConnector</module-name>
  	</required-modules>
  	<critical>false</critical>
  </module>
</module-list>
